version: "2"
services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
        - NODE_ENV=production
    volumes:
        - ./:/home/node/app
    expose:
        - "9999"
    command: "npm start"

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: pass
      ports:
          - '8081:8081'

  mysql:
    image: mysql:8.0.18
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass